title: BonaniTech
email:
description: >-
baseurl: ""
url: "https://bonani.tech"
twitter_username: mbonani
github_username:  bonanitech

permalink: /:title/
timezone: America/New_York
paginate: 5
paginate_path: "/page/:num"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

defaults:
  # Defaults for all pages
  - scope:
      path: ""
    values:
      layout: page
      comments: false
  # Defaults for blog posts
  - scope:
      path: "_posts"
    values:
      layout: post
      comments: true

collections:
  swap:
    output: true
